config/routes.rb
ChartkickDemo::Application.routes.draw do
  root to: "visits#show"

  resource :visit do 
    member do
      get :visits_by_day
      get :visits_by_country_day
    end
  end

  

end

app/models/visit.rb
class Visit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def show
    @visits = Visit.all
  end

  def visits_by_day
    render json: Visit.group_by_day(:visited_at, format: "%B %d, %Y").count
  end

  def visits_by_country_day
  	render json: Visit.group(:country).group_by_day(:visited_at, format: "%B %d, %Y").count.chart_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChartkickDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/visits/show.html.erb
<div class="row">
  <!-- Line Chart - Single Series -->
  <div class="col-xs-6">
    <h3>Visits By Day</h3>
    <%= line_chart @visits.group_by_day(:visited_at, format: "%B %d, %Y").count, discrete: true %>
  </div>

  <!-- Line Chart - Multiple Series -->
  <div class="col-xs-6">
    <h3>Visits By Country Per Day</h3>
    <%= line_chart   Visit.pluck("country").uniq.map { |c| { name: c, data: @visits.where(country: c).group_by_day(:visited_at, format: "%B %d, %Y").count }  }, discrete: true %>
  </div>
</div>

<div class="row">

  <div class="col-xs-6">
   <h3>Visits By Country Per Day (Coded differently 1)</h3>
   <%= line_chart @visits.pluck("country").uniq.map { |c| { name: c, data: Visit.where(country: c).group_by_day(:visited_at, format: "%B %d, %Y").count } }, discrete: true %>
  </div>

  <div class="col-xs-6">
   <h3>Visits By Country Per Day (Coded differently 2)</h3>
   <%= line_chart Visit.group(:country).group_by_day(:visited_at, format: "%B %d, %Y").count, discrete: true %>
  </div>
  
</div>

<div class="row">
  <!-- Pie Chart -->
  <div class="col-xs-6">
    <h3>Total Visits by Country</h3>
    <%= pie_chart @visits.group(:country).count %>
  </div>

  <!-- Geo Chart --> 
  <div class="col-xs-6">
    <h3>Visits By Day</h3>
    <%= geo_chart @visits.group(:country).count %>
  </div>

</div>

<div class="row">
  <!-- area chart --> 
  <div class="col-xs-12">
    <h3>Total Load Time By Day</h3>
    <%= area_chart @visits.group_by_day(:visited_at).maximum(:load_time) %>
  </div>
</div>

<div class="row">
  <!-- Column Chart --> 
  <div class="col-xs-6">
    <h3>Total Visits Per Country</h3>
    <%= column_chart @visits.group(:country).count %>
  </div>
  <!-- Bar Chart --> 
  <div class="col-xs-6">
    <h3>Total Visits Per Country</h3>
    <%= bar_chart @visits.group(:country).count %>
  </div>
</div>

<!-- Line Chart - Single Series -->
<div class="col-xs-12">
  <h3>Visits By Day (AJAX Call)</h3>
  <%= line_chart visits_by_day_visit_path %>
</div>

<div class="col-xs-12">
   <h3>Visits By Country Per Day (AJAX Call)</h3>
   <%= line_chart visits_by_country_day_visit_path %>
</div>